"Contains teh names of the train and test games"

# Test games:
bin_to_name = {}    # Binary to 
bin_to_name["alien"] = "Alien"
bin_to_name["amidar"] = "Amidar"
bin_to_name["assault"] = "Assault"
bin_to_name["astroids"] = "Asteroids"
bin_to_name["atlantis"] = "Atlantis"
bin_to_name["bank_heist"] = "Bank Heist"
bin_to_name["battle_zone"] = "Battlezone"
bin_to_name["beam_rider"] = "Beamrider"
bin_to_name["berzerk"] = "Berzerk"
bin_to_name["bowling"] = "Bowling"
bin_to_name["boxing"] = "Boxing"
bin_to_name["carnival"] = "Carnival"
bin_to_name["centipede"] = "Centipede"
bin_to_name["chopper_command"] = "Chopper Command"
bin_to_name["crazy_climber"] = "Crazy Climber"
bin_to_name["demon_attack"] = "Demon Attack"
bin_to_name["double_dunk"] = "Double Dunk"
bin_to_name["elevator_action"] = "Elevator Action"
bin_to_name["enduro"] = "Enduro"
bin_to_name["fishing_derby"] = "Fishing Derby"
bin_to_name["frostbite"] = "Frostbite"
bin_to_name["gopher"] = "Gopher"
bin_to_name["gravitar"] = "Gravitar"
bin_to_name["hero"] = "H.E.R.O."
bin_to_name["ice_hockey"] = "Ice Hockey"
bin_to_name["jamesbond"] = "James Bond 007"
bin_to_name["journey_escape"] = "Journey Escape"
bin_to_name["kangaroo"] = "Kangaroo"
bin_to_name["krull"] = "Krull"
bin_to_name["kung_fu_master"] = "Kung-Fu Master"
bin_to_name["montezuma_revenge"] = "Montezuma's Revenge: Starring Panama Joe"
bin_to_name["ms_pacman"] = "Ms. Pac-Man"
bin_to_name["name_this_game"] = "Name This Game"
bin_to_name["phoenix"] = "Phoenix"
bin_to_name["pitfall"] = "Pitfall II: Lost Caverns"
bin_to_name["pitfall2"] = "Pitfall!"
bin_to_name["pooyan"] = "Pooyan"
bin_to_name["private_eye"] = "Private Eye"
bin_to_name["riverraid"] = "River Raid"
bin_to_name["road_runnerr"] = "Road Runner"
bin_to_name["robotank"] = "Robot Tank"
bin_to_name["skiing"] = "Skiing"
bin_to_name["solaris"] = "Solaris"
bin_to_name["star_gunner"] = "Stargunner"
bin_to_name["tennis"] = "Tennis"
bin_to_name["time_pilot"] = "Time Pilot"
bin_to_name["tutankham"] = "Tutankham"
bin_to_name["up_n_down"] = "Up'n Down"
bin_to_name["video_pinball"] = "Video Pinball"
bin_to_name["zaxxon"] = "Zaxxon"

test_games = bin_to_name.keys()
test_games.sort()

# Add train games
bin_to_name['freeway'] = "Freeway"
bin_to_name['asterix'] = "Asterix"
bin_to_name['seaquest'] = "Seaquest"
bin_to_name['space_invaders'] = "Space Invaders"

train_games = ['freeway', 'asterix', 'seaquest', 'space_invaders']